grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort

prometheus:
  service:
    type: NodePort
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

crds:
  enabled: false