apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-app
        image: bdv1234/order-app:6430767648bcdcb85c2d66ba70ec1b30193e9dc9
        env:
        - name: DATABASE_URL
          value: mysql+pymysql://order_user:order_pass@mysql:3309/orders
        ports:
        - containerPort: 8000
